### ISSUE TITLE
[tracker] Dicoogle API changes

### ISSUE THREAD

**Issue by Enet4** [bioinformatics-ua/dicoogle#207]
Let us use this issue to keep track of all proposed and planned changes to our public APIs when making the transition to future major version. This looks better than making a milestone because then we have a place to discuss proposals. Also, some major extensions to the API may become available in minor versions if they don't break backwards compatibility.

**Planned:**
- [ ] Correct web service error reporting - #193
- [ ] Rethink the index report - #163 
- [ ] Capability to extend and access some core classes from Plugins - #128 
- [ ] Rearrange plugin service endpoints - #123 
- [ ] Error handling on query operations.

**In review:**
- [ ] Acknowledge which query providers list DICOM meta-data -  #122 
- [ ] Plugin set development improvements - #115 
- [ ] Dynamic Plugin configuration - #103 

I will close #11 and let that discussion continue here.
